// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn7yN5eXZl3FkB-WJ2EFkbqTdapHz2H7A',
    appId: '1:323501729844:web:c5cb1fcb54affb869b0261',
    messagingSenderId: '323501729844',
    projectId: 'camera-497e9',
    authDomain: 'camera-497e9.firebaseapp.com',
    storageBucket: 'camera-497e9.firebasestorage.app',
    measurementId: 'G-7RQTD8E2ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSiQ3c2d6IL958b479-lkjR1CSwjC053s',
    appId: '1:323501729844:android:9ada6bccc5d93e3f9b0261',
    messagingSenderId: '323501729844',
    projectId: 'camera-497e9',
    storageBucket: 'camera-497e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXHw0XQ_sUCUe2Lsh0HAUbnqte72PIUA',
    appId: '1:323501729844:ios:27ecd60c4a272ed29b0261',
    messagingSenderId: '323501729844',
    projectId: 'camera-497e9',
    storageBucket: 'camera-497e9.firebasestorage.app',
    iosBundleId: 'com.example.cameraApp',
  );
}
